import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Container, Text, Row, Col } from "@nextui-org/react";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text>Hello there</Text>
      </main>
      <footer className={styles.footer}>
        <Text>Footer Here</Text>
      </footer>
    </Container>
  );
};

export default Home;
